name: vila_tour_pmdm
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_secure_storage: ^9.2.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.8.0
  path_provider: ^2.0.11
  provider: ^6.1.2
  flutter_map_marker_popup: ^7.0.0
  url_launcher: ^6.1.8
  flutter_compass: ^0.8.1
  flutter_polyline_points: ^2.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.0.1+1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  image: null
  branding: "assets/vilatour_branding.png"
  color: "#ffffff"
  android_12:
    image: null
    branding: "assets/vilatour_branding.png"
    color: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.ico"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - data/
    - languages/

  fonts:
    - family: PontanoSans
      fonts:
        - asset: fonts/PontanoSans-VariableFont_wght.ttf
